### ISSUE TITLE
can't save app

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#103] opened 2020-03-16 17:05 UTC
![image](https://user-images.githubusercontent.com/59945434/76782534-ca90fe80-6786-11ea-9bfd-5553cf4d3d68.png)

got to desking stage, cannot save nor submit.

**Comment by bbuchanan** [comment] 2020-03-16 18:40
closing, looks like a duplicate of #105

**Closed as completed by bbuchanan** 2020-03-16 18:40 UTC
